### ISSUE TITLE
Crashes when setting event color to red

### ISSUE THREAD

**Issue by marinabilles** [FossifyOrg/Calendar#202]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

Samsung A52s

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Select an event
2. Click on event color
3. Select red (top left option, see screenshot) (!Important: other colors do not cause this problem)

### Expected behavior

Color changes to red

### Actual behavior

1. The app crashes; OR
2. The event color gets reset immediately upon automatic sync

### Screenshots/Screen recordings

<img alt="Screenshot_20240403_175619_Calendar" src="https://github.com/FossifyOrg/Calendar/assets/5391834/be3aa514-a94c-4fc8-9207-bc323657121b" width=180 />

### Additional information

 I have a CalDAV calendar set up in DAVx5. I have modified the DAVx5 settings, setting "manage calendar colors" to "apps can modify calendar colors" and setting "support for event colors" to ON.

Important: this does only happen if I select the top left most color, in this case red. All the other colors work fine, including similar but different shades of red.

Of note, I found this guide from DAVx5 that provided no help: https://www.davx5.com/faq/setting-event-colors-crash/

**Comment by OlavStornes** [comment]
Happens to me as well, but not with the same color as you.

When assigning colors to a Google-linked calendar, a lot of the gradual colors makes the calendar crash on save (top row, second to the left).

When assigning colors to my Nextcloud-powered calendar (via DavX5), i haven't had this issue pop up yet. I assume that is because nextcloud supports assigning to all colors shown.

Could it be that the colors displayed on Fossify calender is not necessarily supported on the target back end? When assigning colors via Etar, my option is 11 different colors which works without any issues. In contrast Fossify shows me every possibillity, same as the screenshot of OP.

**Comment by Aga-C** [comment]
@marinabilles Where do you keep your CalDAV synced calendar? Google, NextCloud, or somewhere else?

**Comment by marinabilles** [comment]
@Aga-C It's hosted by an email provider, so "somewhere else".

**Comment by naveensingh** [comment]
I could not reproduce this but it might be fixed in https://github.com/FossifyOrg/Calendar/releases/tag/1.2.0

**Comment by naveensingh** [comment]
Closed because it should be fixed in 1.2.0 but if anybody still has this problem, please let me know.

**Comment by Agathioux** [comment]
I have version 1.8.0 and still have the problem for any given color change. The app crashes when I change the color of an existing event.  When I change the colour of an event I am creating and then save it, the event appears for 1 second on the calendar and then disappears and is never actually saved. This happens both on my camendar and on a shared calendar hosted by nexcloud.
