### ISSUE TITLE
Overnight switching of day / date

### ISSUE THREAD

**Issue by cd-FileX** [FossifyOrg/Calendar#253]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 10

### Affected device model

DOOGEE S88+

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open the app at 23:59
(1.1 Switch app / to home /..)
2. Wait 1 Minute
3. Date doesn't switch to new day's number

### Expected behavior

If today is 29. January and yesterday was 28., then that the date marker switches from 28. To 29.

### Actual behavior

Stays on 28.

### Additional information

Viewed the calendar the day the before and let it open in background. Usually gets killed, though this time it stayed open and as I switched to it the next day I was in confusion why it shows the wrong date.
Will test it out today again if and how it works.

**Comment by naveensingh** [comment]
This "bug" also affects other views as noted in https://github.com/FossifyOrg/Calendar/issues/481 and should be "fixed" in every view.

**Comment by cinnabar777** [comment]
Bummer this is still open. I uninstalled for a while and just reinstalled thinking it would be fixed by now....

**Comment by cinnabar777** [comment]
Yep, it's still happening. No update unless app launched. 

Android 15 GrapheneOS
V1. 2.0
Fresh install

Seen an article saying 15 may require persistent notification for widgets to properly update 🤦🏼‍♂️

🤷🏼‍♂️

**Comment by naveensingh** [comment]
> Seen an article saying 15 may require persistent notification for widgets to properly update 🤦🏼‍♂️ 

Yeah, those breaking changes happen every year now. Targeting Android 15 is still on my TODO list, I hope to get it done soon.

**Comment by cinnabar777** [comment]
@naveensingh 

I tested [min calendar widget](https://github.com/mvmike/min-cal-widget) and it's working fine. Maybe helpful? 🤷🏼‍♂️

**Comment by naveensingh** [comment]
Maybe. I haven't investigated this properly yet but it should get fixed by the next release.

**Comment by cinnabar777** [comment]
I've found a fix! At least on GrapheneOS

Generally I have calendar storage disabled because the system calendar app doesn't function and I use Fossify calendar internal storage, not the system. 

When using the mini calendar widget it needed events in the system calendar storage so I imported them with the ics importer off f-droid.org 

I also set Fossify to use that internal system calendar via CalDav sync. Since then it has properly updated the widget overnight!

🎆🎇

**Comment by Semuria** [comment]
> Maybe. I haven't investigated this properly yet but it should get fixed by the next release.

My calendar Widget showed me rn that we are on Monday despite its Wednesday so its still occuring

**Comment by naveensingh** [comment]
Yeah, couldn't get to it in time.

**Comment by Semuria** [comment]
I noticed that the saved appointments are also affected. Unfortunately, they got saved 1-2 days before the configured date.

**Comment by Semuria** [comment]
2 month that this was assigned @naveensingh 
Is there any progress expectable soon? 
Otherwise I would have to quit due to endless failed appointments and till today not being aware that Fossify Calendar is truly somewhere between Alpha and Beta stage and not reliable

**Comment by naveensingh** [comment]
> I noticed that the saved appointments are also affected. Unfortunately, they got saved 1-2 days before the configured date.

> endless failed appointments

That does not seem related to this issue. This issue is strictly about automatically updating the UI when the date changes.

**Comment by Aga-C** [comment]
> My calendar Widget showed me rn that we are on Monday despite its Wednesday so its still occuring

https://github.com/FossifyOrg/Calendar/issues/164
